myproject/core/urls.py
from myproject.core import views as v
from django.urls import path

app_name = 'core'

urlpatterns = [
    path('', v.index, name='index'),
    path('videos/add/', v.VideoCreate.as_view(), name='video_add'),
    path('videos/<int:pk>/like/', v.video_like, name='video_like'),
    path('videos/<int:pk>/unlike/', v.video_unlike, name='video_unlike'),
    path('themes/', v.themes, name='themes'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('myproject.core.urls')),
    path('admin/', admin.site.urls),
]

myproject/core/models.py
from django.db import models

class Theme(models.Model):
    title = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.title

class Video(models.Model):
    title = models.CharField(max_length=100, unique=True)
    theme = models.ForeignKey(Theme, on_delete=models.CASCADE)
    like = models.PositiveIntegerField(default=0)
    unlike = models.PositiveIntegerField(default=0)
    score = models.FloatField(default=0)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.score = int(self.like) - int(self.unlike) / 2
        super(Video, self).save(*args, **kwargs)

myproject/core/forms.py
from django import forms
from myproject.core.models import Video


class VideoForm(forms.ModelForm):

    class Meta:
        model = Video
        fields = '__all__'

myproject/core/views.py
from django.db.models import Max
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView
from myproject.core.forms import VideoForm
from myproject.core.models import Video


def index(request):
    videos = Video.objects.all()
    context = {'videos': videos}
    return render(request, 'index.html', context)


class VideoCreate(CreateView):
    model = Video
    template_name = 'add.html'
    form_class = VideoForm
    success_url = '/'


@csrf_exempt
def video_like(request, pk):
    if request.method == 'POST' and request.is_ajax():
        data = request.POST
        like = data.get('like')
        video = Video.objects.get(pk=pk)
        video.like = like
        video.save()
        response = {'data': video.like}
        return JsonResponse(response)


@csrf_exempt
def video_unlike(request, pk):
    if request.method == 'POST' and request.is_ajax():
        data = request.POST
        unlike = data.get('unlike')
        video = Video.objects.get(pk=pk)
        video.unlike = unlike
        video.save()
        response = {'data': video.unlike}
        return JsonResponse(response)


def themes(request):
    template_name = 'themes.html'
    themes = Video.objects.values('theme__title').annotate(Max('score'))\
        .order_by('-score__max')
    context = {'themes': themes}
    return render(request, template_name, context)

myproject/core/templates/add.html
{% extends "base.html" %}

{% block content %}

{% load widget_tweaks %}

<style>
  span.required:after {
    content: "*";
    color: red;
  }
</style>

<form method="POST">
    {% csrf_token %}
    {% for field in form.visible_fields %}
      <div class="form-group{% if field.errors %} has-error {% endif %}">
        <label for="{{ field.id_for_label }}">
          {% if field.field.required %}
            <span class="required">{{ field.label }} </span>
          {% else %}
            {{ field.label }}
          {% endif %}
        </label>
        {% render_field field class="form-control" %}
        {% for error in field.errors %}
          <span class="text-muted">{{ error }}</span>
        {% endfor %}
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-success">Save</button>
</form>

{% endblock content %}

myproject/core/templates/base.html
<!-- https://getbootstrap.com/docs/4.0/getting-started/introduction/#starter-template -->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">
  <!-- <link rel="shortcut icon" href="http://html5-training-in-hyderabad.blogspot.com.br/favicon.ico"> -->
  <title>New Project</title>
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <!-- Font-awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  <style>
    body {
      margin-top: 60px;
    }
  </style>

  {% block css %}{% endblock css %}

  </body>
</head>
<body>

  {% include "nav.html" %}

  <div class="container">
    {% block content %}{% endblock content %}
  </div>

  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

  {% block js %}{% endblock js %}

</body>
</html>

myproject/core/templates/index.html
{% extends "base.html" %}

{% block content %}
  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <div class="container">
      <h1>Welcome!</h1>
      <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
      <p>
        <a href="{% url 'core:video_add' %}">
          <button class="btn btn-primary btn-lg" type="button">
          Add Video &raquo;
          </button>
        </a>
      </p>
    </div>
  </div>

  <div class="text-center mt-5 pt-5">
    <table class="table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Theme</th>
        </tr>
      </thead>
      <tbody>
        {% for video in videos %}
          <tr>
            <td>{{ video.title }}</td>
            <td>{{ video.theme }}</td>
            <td>
              <i class="fa fa-thumbs-up likeCount" style="color: blue" data-id="{{ video.id }}"></i>
            </td>
            <td id="like_{{ video.id }}" style="padding-right: 10px">{{ video.like }}</td>
            <td id="thumbs_dow_{{ video.id }}">
              <i class="fa fa-thumbs-down unlikeCount" style="color: blue" data-id="{{ video.id }}"></i>
            </td>
            <td id="unlike_{{ video.id }}">{{ video.unlike }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock content %}

{% block js %}

<script>
  var like=0;
  var unlike=0;

  $('.likeCount').on('click', function () {
    var likeId = $(this).data('id')
    like = $("#like_" + likeId).text()
    like++
    $("#like_" + likeId).html(like)

    let url = "/videos/" + likeId + "/like/"
    $.ajax({
      url: url,
      type: 'POST',
      data: {
        like: like
      },
      success: function(response) {
        like = response.data
      }
    })
  });

  $('.unlikeCount').on('click', function () {
    var unlikeId = $(this).data('id')
    unlike = $("#unlike_" + unlikeId).text()
    unlike++
    $("#unlike_" + unlikeId).html(unlike)

    let url = "/videos/" + unlikeId + "/unlike/"
    $.ajax({
      url: url,
      type: 'POST',
      data: {
        unlike: unlike
      },
      success: function(response) {
        unlike = response.data
      }
    })
  });

</script>

{% endblock js %}

myproject/core/templates/nav.html
<!-- https://getbootstrap.com/docs/4.0/examples/starter-template/ -->
<!-- https://github.com/JTruax/bootstrap-starter-template/blob/master/template/start.html -->

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'core:index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:themes' %}">Themes</a>
                </li>
            </ul>
        </div>
    </nav>

myproject/core/templates/themes.html
{% extends "base.html" %}

{% block content %}

<div class="text-center mt-5 pt-5">
  <table class="table">
    <thead>
      <tr>
        <th>Theme</th>
        <th>Score</th>
      </tr>
    </thead>
    <tbody>
      {% for theme in themes %}
        <tr>
          <td>{{ theme.theme__title }}</td>
          <td>{{ theme.score__max }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>


{% endblock content %}